name: Lazarus CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: Configurar Lazarus e FPC
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: '2.2.0'

    - name: Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências Python
      run: pip install tqdm
      
    - name: Executar script de alteração do ACBr
      run: |
        cd project
        yes s | python script_altera_acbr.py ../acbr/Fontes/ACBrDFe/
      
    - name: Compilar o projeto para Linux
      run: |
        cd project
        lazbuild -B ACBRWebService.lpi

    - name: Upload do executável de Linux (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Linux
        path: project/bin/ACBRWebService

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: Configurar Lazarus, FPC e o Cross-Compiler
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: '2.2.0'
        with-cross-bits: '64'
        with-cross-os: 'win'

    - name: Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências Python
      run: pip install tqdm
      
    - name: Executar script de alteração do ACBr
      run: |
        cd project
        yes s | python script_altera_acbr.py ../acbr/Fontes/ACBrDFe/
      
    - name: Compilar o projeto para Windows 64-bit
      run: |
        cd project
        lazbuild -B --os=win64 --cpu=x86_64 ACBRWebService.lpi

    - name: Upload do executável de Windows (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Win64
        path: project/bin/ACBRWebService.exe
