name: Lazarus CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  # Job para compilar a versão de Linux
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: 2. Configurar Lazarus e FPC
      uses: gcarreno/setup-lazarus@v1
      with:
        lazarus-version: '2.2.0'
        fpc-version: '3.2.0'

    - name: 3. Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson

    - name: 4. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 5. Remover a referência ao gbswagger do .lpi
      run: |
        cd project
        sed -i '/gbswagger/d' ACBRWebService.lpi
      
    - name: 6. Executar script de alteração do ACBr
      run: |
        cd project
        # O comando 'yes' responde 's' (sim) para as perguntas do script
        yes | python script_altera_acbr.py
      
    - name: 7. Compilar o projeto para Linux
      run: |
        cd project
        lazbuild ACBRWebService.lpi

    - name: 8. Upload do executável de Linux (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Linux
        path: bin/ACBRWebService

  # Job para compilar a versão de Windows (EXE)
  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: 2. Configurar Lazarus, FPC e o Cross-Compiler para Windows
      run: |
        sudo apt-get update
        sudo apt-get install -y fpc-3.2.0 lazarus-2.2.0 fpc-source-3.2.0 fp-compiler-3.2.0 fp-units-rtl-3.2.0
        # Instala o cross-compiler para gerar o .exe de 64-bits
        sudo apt install -y fpc-cross-x86-64-win64

    - name: 3. Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson

    - name: 4. Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'


    - name: 5. Executar script de alteração do ACBr
      run: |
        cd project
        yes | python script_altera_acbr.py
      
    - name: 6. Compilar o projeto para Windows 64-bit
      run: |
        cd project
        # Usa --os e --cpu para especificar o alvo da compilação
        lazbuild --os=win64 --cpu=x86_64 ACBRWebService.lpi

    - name: 7. Upload do executável de Windows (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Win64
        path: bin/ACBRWebService.exe
