name: Lazarus CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: Configurar Lazarus e FPC
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: '2.2.0'

    - name: Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson
        git clone https://github.com/fortesinformatica/fortesreport-ce ../fortesreport-ce4

    - name: Compilar pacotes de dependência
      run: |
        # Dependências primárias
        lazbuild -B ../acbr/Pacotes/Lazarus/synapse/laz_synapse.lpk
        lazbuild -B ../fortesreport-ce4/Packages/frce.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrComum/ACBrComum.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrOpenSSL/ACBrOpenSSL.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDiversos/ACBrDiversos.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrTCP/ACBrTCP.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/PCNComum/PCNComum.lpk
        
        # Dependências DFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrDFeComum.lpk
        
        # NFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrNFe/ACBr_NFe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrNFe/DANFE/NFe/Fortes/ACBr_NFe_DanfeRL.lpk
        
        # CTe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrCTe/ACBr_CTe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrCTe/DACTE/Fortes/ACBr_CTe_DACTeRL.lpk
        
        # MDFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrMDFe/ACBr_MDFe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrMDFe/DAMDFE/Fortes/ACBr_MDFe_DAMDFeRL.lpk

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências Python
      run: pip install tqdm
      
    - name: Executar script de alteração do ACBr
      run: |
        cd project
        # O 'yes s' responde 's' (sim) para a pergunta sobre subdiretórios no script
        yes s | python script_altera_acbr.py ../acbr/Fontes/ACBrDFe/
      
    - name: Compilar o projeto para Linux
      run: |
        cd project
        lazbuild -B ACBRWebService.lpi

    - name: Upload do executável de Linux (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Linux
        path: project/bin/ACBRWebService

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código do projeto
      uses: actions/checkout@v4
      with:
        path: 'project'

    - name: Configurar Lazarus, FPC e o Cross-Compiler
      uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: '2.2.0'
        with-cross-bits: '64'
        with-cross-os: 'win'

    - name: Checkout das dependências
      run: |
        git clone https://github.com/ProjetoACBr/ACBr.git ../acbr
        git clone https://github.com/HashLoad/horse.git ../horse-master
        git clone https://github.com/HashLoad/handle-exception.git ../handle-exception
        git clone https://github.com/HashLoad/jhonson.git ../jhonson
        git clone https://github.com/fortesinformatica/fortesreport-ce ../fortesreport-ce4

    - name: Instalar dependências do sistema
      run: sudo apt-get update && sudo apt-get install -y binutils

    - name: Compilar pacotes de dependência
      run: |
        # Dependências primárias
        lazbuild -B ../acbr/Pacotes/Lazarus/synapse/laz_synapse.lpk
        lazbuild -B ../fortesreport-ce4/Packages/frce.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrComum/ACBrComum.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrOpenSSL/ACBrOpenSSL.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDiversos/ACBrDiversos.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrTCP/ACBrTCP.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/PCNComum/PCNComum.lpk
        
        # Dependências DFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrDFeComum.lpk
        
        # NFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrNFe/ACBr_NFe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrNFe/DANFE/NFe/Fortes/ACBr_NFe_DanfeRL.lpk
        
        # CTe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrCTe/ACBr_CTe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrCTe/DACTE/Fortes/ACBr_CTe_DACTeRL.lpk
        
        # MDFe
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrMDFe/ACBr_MDFe.lpk
        lazbuild -B ../acbr/Pacotes/Lazarus/ACBrDFe/ACBrMDFe/DAMDFE/Fortes/ACBr_MDFe_DAMDFeRL.lpk

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências Python
      run: pip install tqdm
      
    - name: Executar script de alteração do ACBr
      run: |
        cd project
        yes s | python script_altera_acbr.py ../acbr/Fontes/ACBrDFe/
      
    - name: Compilar o projeto para Windows 64-bit
      run: |
        cd project
        lazbuild -B --os=win64 --cpu=x86_64 ACBRWebService.lpi

    - name: Upload do executável de Windows (Artefato)
      uses: actions/upload-artifact@v4
      with:
        name: ACBRWebService-Win64
        path: project/bin/ACBRWebService.exe